# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-05 03:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='标题')),
                ('content', models.TextField(verbose_name='正文')),
                ('create_time', models.DateField(auto_now_add=True, verbose_name='创建时间')),
                ('last_revise_time', models.DateField(auto_now=True, verbose_name='修改时间')),
                ('state', models.CharField(choices=[('p', 'Publish'), ('d', 'Draft')], max_length=1, verbose_name='文章状态')),
            ],
            options={
                'ordering': ['-last_revise_time'],
            },
        ),
    ]
