# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-11 04:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='分类名称')),
                ('created_time', models.DateField(auto_now_add=True, verbose_name='创建时间')),
                ('last_revise_time', models.DateField(auto_now=True, verbose_name='修改时间')),
            ],
        ),
        migrations.AlterField(
            model_name='article',
            name='state',
            field=models.CharField(choices=[('d', 'Draft'), ('p', 'Publish')], max_length=1, verbose_name='文章状态'),
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='article.Category', verbose_name='分类'),
        ),
    ]
